OPENAI_API_KEY = ""
OPENAI_MODEL = "gpt-3.5-turbo"

NEO4J_URI = "bolt://18.208.210.93:7687"
NEO4J_USERNAME = "neo4j"
NEO4J_PASSWORD = "treatment-radiuses-majority"

NEO4J_URI_AURA="neo4j+s://ab32fb62.databases.neo4j.io"
NEO4J_PASSWORD_AURA="9SUIUN4y90znQnke5ptY0_jJm9dC2yHPIG9D9xeBlv8"